import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";

const geistSans = Noto_Sans_Thai({
  subsets: ["thai"],
});

export const metadata: Metadata = {
  title: "แฟ้มสะสมผลงานของเหม่ง",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} bg-violet-500/5`}>{children}</body>
    </html>
  );
}
